version: '3.8'
services:
  consul:
    image: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
      - 8301:8301
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
  coredns:
    image: coredns-consul
    build: .
    ports:
      - 8053:53/udp
    environment:
      CONSUL_ADDRESS: 172.17.0.1
    depends_on:
      - consul
